name: Manual Trigger Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate_token.outputs.token }}
          approvers: Yavhan
          minimum-approvals: 1
