name: Manual Trigger Workflow

on:
  workflow_dispatch: # Manually trigger the workflow
  # Add other triggers for automatic runs here if needed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # Define steps for the first job here
      - name: Step 1 of Job 1
        run: echo "This is Job 1, Step 1"
      - name: Step 2 of Job 1
        run: echo "This is Job 1, Step 2"
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      # Define steps for the second job here
      - name: Step 1 of Job 2
        run: echo "This is Job 2, Step 1"
      - name: Step 2 of Job 2
        run: echo "This is Job 2, Step 2"

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2] # Waits for both job1 and job2 to finish
    if: github.event_name == 'workflow_dispatch' # Only runs on manual trigger
    steps:
      # Define steps for the third job here
      - name: Step 1 of Job 3
        run: echo "This is Job 3, Step 1"
      - name: Step 2 of Job 3
        run: echo "This is Job 3, Step 2"
