name: Manual Trigger Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      # Define steps for the first job here
      - name: Step 1 of Job 1
        run: echo "This is Job 1, Step 1"
      - name: Step 2 of Job 1
        run: echo "This is Job 1, Step 2"
      
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      # Define steps for the second job here
      - name: Step 1 of Job 2
        run: echo "This is Job 2, Step 1"
      - name: Step 2 of Job 2
        run: echo "This is Job 2, Step 2"

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2] # Waits for both job1 and job2 to finish
    if: github.event_name != 'pull_request' # Only runs for pushes, not for pull requests
    steps:
      # Define steps for the third job here
      - name: Step 1 of Job 3
        run: echo "This is Job 3, Step 1"
      - name: Step 2 of Job 3
        run: echo "This is Job 3, Step 2"

  manual_approval:
    needs: job3
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' # Only runs for pushes, not for pull requests
    steps:
      - name: Manual Approval
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.workflow_runs.listForWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow,
              status: "queued"
            });

            if (response.data.total_count === 0) {
              core.setFailed("No queued workflow runs found.");
            } else {
              console.log("Workflow can be triggered.");
            }
